const now = new Date();
const today = new Date(now);
today.setHours(23, 59, 0, 0);

const todayStr = today.toISOString();

function hoursFromNow(h) {
  const d = new Date(now);
  d.setHours(d.getHours() + h);
  return d.toISOString();
}

function todayAt(h, m = 0) {
  const d = new Date(now);
  d.setHours(h, m, 0, 0);
  return d.toISOString();
}

export const products = [
  {
    id: 1,
    name: '닭가슴살 샐러드',
    store: '그린샐러드 강남점',
    storeId: 1,
    distance: 450,
    thumbnail: null,     // 판매자 앱에서 대표사진 등록 시 URL 저장
    emoji: '🥗',         // thumbnail 없을 때 표시할 이모지 폴백
    images: [],          // { url: string, isThumbnail: boolean }[] — 최대 10장
    category: '샐러드',
    originalPrice: 8900,
    salePrice: 4900,
    discountRate: 45,
    stock: 3,
    pickupStart: todayAt(18),
    pickupEnd: todayAt(20),
    expiryDate: todayStr,
    storage: '냉장 보관',
    status: 'selling',
    badges: ['오늘까지', '마감임박'],
    description: '신선한 닭가슴살과 야채로 구성된 건강 샐러드입니다.',
    composition: '닭가슴살 150g, 로메인 80g, 방울토마토 30g, 드레싱 15ml',
    origin: '닭가슴살 국내산, 채소 국내산',
    allergyInfo: '달걀, 대두, 밀 함유',
    storageMethod: '냉장(0~5°C) 보관, 개봉 후 즉시 섭취 권장',
    pickupAddress: '서울 강남구 테헤란로 123',
    cancelPolicy: '픽업 전까지 취소 가능. 픽업 후 단순 변심 환불 불가.',
    storeNotice: '픽업 시 영수증 또는 픽업번호를 보여주세요.',
    lat: 37.5012,
    lng: 127.0396,
    liked: false,
  },
  {
    id: 2,
    name: '통밀 크로와상 2개입',
    store: '베이커리온 역삼점',
    storeId: 2,
    distance: 280,
    thumbnail: null,
    emoji: '🥐',
    images: [],
    category: '빵',
    originalPrice: 4800,
    salePrice: 1900,
    discountRate: 60,
    stock: 5,
    pickupStart: todayAt(17),
    pickupEnd: todayAt(21),
    expiryDate: todayStr,
    storage: '실온 보관',
    status: 'selling',
    badges: ['오늘까지', '할인60%'],
    description: '바삭하고 고소한 통밀 크로와상입니다.',
    composition: '통밀 크로와상 2개',
    origin: '밀 국내산',
    allergyInfo: '밀, 달걀, 유제품 함유',
    storageMethod: '실온 보관, 당일 섭취 권장',
    pickupAddress: '서울 강남구 역삼로 45',
    cancelPolicy: '픽업 전까지 취소 가능. 픽업 후 단순 변심 환불 불가.',
    storeNotice: '재고 소진 시 조기 마감될 수 있습니다.',
    lat: 37.5008,
    lng: 127.0368,
    liked: false,
  },
  {
    id: 3,
    name: '한식 도시락 (불고기)',
    store: '한솥도시락 강남역점',
    storeId: 3,
    distance: 720,
    thumbnail: null,
    emoji: '🍱',
    images: [],
    category: '도시락',
    originalPrice: 7500,
    salePrice: 3500,
    discountRate: 53,
    stock: 0,
    pickupStart: todayAt(16),
    pickupEnd: todayAt(19),
    expiryDate: todayStr,
    storage: '냉장 보관',
    status: 'soldout',
    badges: ['품절'],
    description: '부드러운 불고기와 반찬이 포함된 한식 도시락입니다.',
    composition: '불고기 120g, 밥 200g, 반찬 3종',
    origin: '소고기 국내산, 쌀 국내산',
    allergyInfo: '밀, 대두 함유',
    storageMethod: '냉장(0~5°C) 보관',
    pickupAddress: '서울 강남구 강남대로 396',
    cancelPolicy: '픽업 전까지 취소 가능.',
    storeNotice: '',
    lat: 37.4979,
    lng: 127.0276,
    liked: false,
  },
  {
    id: 4,
    name: '딸기 생크림 케이크 조각',
    store: '파리바게뜨 선릉점',
    storeId: 4,
    distance: 950,
    thumbnail: null,
    emoji: '🍰',
    images: [],
    category: '디저트',
    originalPrice: 5500,
    salePrice: 2200,
    discountRate: 60,
    stock: 2,
    pickupStart: todayAt(19),
    pickupEnd: todayAt(21, 30),
    expiryDate: todayStr,
    storage: '냉장 보관',
    status: 'selling',
    badges: ['마감임박', '오늘까지'],
    description: '신선한 딸기와 부드러운 생크림이 어우러진 케이크입니다.',
    composition: '케이크 조각 1개 (약 150g)',
    origin: '딸기 국내산, 달걀 국내산',
    allergyInfo: '밀, 달걀, 유제품 함유',
    storageMethod: '냉장(0~5°C) 보관',
    pickupAddress: '서울 강남구 선릉로 100',
    cancelPolicy: '픽업 전까지 취소 가능. 픽업 후 단순 변심 환불 불가.',
    storeNotice: '',
    lat: 37.5044,
    lng: 127.0491,
    liked: true,
  },
  {
    id: 5,
    name: '두부 반찬 세트',
    store: '자연반찬 강남점',
    storeId: 5,
    distance: 600,
    thumbnail: null,
    emoji: '🥡',
    images: [],
    category: '반찬',
    originalPrice: 6000,
    salePrice: 2500,
    discountRate: 58,
    stock: 4,
    pickupStart: todayAt(17),
    pickupEnd: todayAt(20),
    expiryDate: todayStr,
    storage: '냉장 보관',
    status: 'selling',
    badges: ['오늘까지'],
    description: '국산 두부로 만든 건강한 반찬 세트입니다.',
    composition: '두부조림 100g, 시금치나물 80g, 콩나물무침 80g',
    origin: '두부 국내산, 채소 국내산',
    allergyInfo: '대두 함유',
    storageMethod: '냉장(0~5°C) 보관',
    pickupAddress: '서울 강남구 논현로 123',
    cancelPolicy: '픽업 전까지 취소 가능.',
    storeNotice: '',
    lat: 37.5021,
    lng: 127.0312,
    liked: false,
  },
  {
    id: 6,
    name: '아메리카노 + 샌드위치 세트',
    store: '카페블랑 강남점',
    storeId: 6,
    distance: 330,
    thumbnail: null,
    emoji: '☕',
    images: [],
    category: '음료',
    originalPrice: 9800,
    salePrice: 4500,
    discountRate: 54,
    stock: 6,
    pickupStart: todayAt(15),
    pickupEnd: todayAt(18),
    expiryDate: todayStr,
    storage: '냉장 보관',
    status: 'selling',
    badges: ['오늘픽업', '할인54%'],
    description: '시원한 아메리카노와 신선한 샌드위치 세트입니다.',
    composition: '아이스 아메리카노 1잔, 클럽 샌드위치 1개',
    origin: '원두 에티오피아산, 채소 국내산',
    allergyInfo: '밀, 달걀 함유',
    storageMethod: '냉장 보관, 당일 섭취',
    pickupAddress: '서울 강남구 역삼로 12',
    cancelPolicy: '픽업 전까지 취소 가능.',
    storeNotice: '음료는 픽업 시 제조됩니다.',
    lat: 37.4993,
    lng: 127.0348,
    liked: false,
  },
];

export const stores = [
  { id: 1, name: '그린샐러드 강남점',  lat: 37.5012, lng: 127.0396, category: '샐러드', productCount: 3, pickupTime: '18:00~20:00', distance: 450,  status: 'selling' },
  { id: 2, name: '베이커리온 역삼점',  lat: 37.5008, lng: 127.0368, category: '빵',    productCount: 5, pickupTime: '17:00~21:00', distance: 280,  status: 'selling' },
  { id: 3, name: '한솥도시락 강남역점', lat: 37.4979, lng: 127.0276, category: '도시락', productCount: 0, pickupTime: '16:00~19:00', distance: 720,  status: 'soldout' },
  { id: 4, name: '파리바게뜨 선릉점',  lat: 37.5044, lng: 127.0491, category: '빵',    productCount: 2, pickupTime: '19:00~21:30', distance: 950,  status: 'closing' },
  { id: 5, name: '자연반찬 강남점',   lat: 37.5021, lng: 127.0312, category: '반찬',   productCount: 4, pickupTime: '17:00~20:00', distance: 600,  status: 'selling' },
  { id: 6, name: '카페블랑 강남점',   lat: 37.4993, lng: 127.0348, category: '음료',   productCount: 6, pickupTime: '15:00~18:00', distance: 330,  status: 'selling' },
];

// ─── 광고 배너 목 데이터 ──────────────────────────────────
// TODO: 관리자 웹에서 등록한 배너를 API로 불러오도록 교체
// 예: const bannerAds = await fetch('/api/banners').then(r => r.json());
// 각 배너 객체 구조:
//   { id, imageUrl, linkType ('category'|'product'|'url'), linkValue, title, description }
// imageUrl이 없을 경우 아래 fallback(그라디언트 + 이모지) 방식을 사용
export const mockBannerAds = [
  {
    id: 1,
    imageUrl: null, // 관리자가 등록한 이미지 URL (없으면 fallback 표시)
    fallback: { bg: 'linear-gradient(135deg, #1A8F5A 0%, #22A06B 100%)', emoji: '🌱' },
    title: '오늘 버려질 수 있는\n음식을 구해보세요',
    description: '최대 70% 할인 · 근처 매장에서 바로 픽업',
    btnLabel: '근처 상품 보기',
    linkType: 'category',
    linkValue: '전체',
  },
  {
    id: 2,
    imageUrl: null,
    fallback: { bg: 'linear-gradient(135deg, #E65C00 0%, #FF8A3D 100%)', emoji: '🥐' },
    title: '베이커리 할인\n오늘만 특가!',
    description: '오늘 구운 빵 최대 60% 할인 · 지금 바로 예약',
    btnLabel: '빵 상품 보기',
    linkType: 'category',
    linkValue: '빵',
  },
  {
    id: 3,
    imageUrl: null,
    fallback: { bg: 'linear-gradient(135deg, #2962FF 0%, #5B8DEF 100%)', emoji: '🍱' },
    title: '오늘의 도시락\n픽업 특가',
    description: '점심·저녁 도시락 최대 50% · 매장 직접 픽업',
    btnLabel: '도시락 보기',
    linkType: 'category',
    linkValue: '도시락',
  },
  {
    id: 4,
    imageUrl: null,
    fallback: { bg: 'linear-gradient(135deg, #6D28D9 0%, #A78BFA 100%)', emoji: '🍰' },
    title: '디저트 마감 할인\n지금 놓치면 아쉬워요',
    description: '케이크·음료 등 오늘 마감 특가 상품 모아보기',
    btnLabel: '디저트 보기',
    linkType: 'category',
    linkValue: '디저트',
  },
];

export const mockOrders = [
  {
    id: 'FP-1024',
    productId: 1,
    productName: '닭가슴살 샐러드',
    store: '그린샐러드 강남점',
    storeAddress: '서울 강남구 테헤란로 123',
    pickupTime: '오늘 18:00~20:00',
    quantity: 1,
    totalPrice: 4900,
    status: 'pending',
    orderedAt: new Date().toISOString(),
  },
  {
    id: 'FP-1018',
    productId: 2,
    productName: '통밀 크로와상 2개입',
    store: '베이커리온 역삼점',
    storeAddress: '서울 강남구 역삼로 45',
    pickupTime: '어제 17:00~21:00',
    quantity: 2,
    totalPrice: 3800,
    status: 'completed',
    orderedAt: new Date(Date.now() - 86400000).toISOString(),
  },
];
